import type {
  Annotation,
  AnnotationKind,
  BlueprintSchema,
  Door,
  DoorSwing,
  DoorType,
  Fixture,
  FixtureKind,
  FloorPlan,
  LegendDefinition,
  LegendItem,
  LineStyle,
  MaterialCategory,
  MaterialDefinition,
  Point2D,
  RenderMode,
  RoofZone,
  Room,
  Wall,
  Window,
  WindowType,
} from "../../types/blueprint";

const DEFAULT_UNITS: BlueprintSchema["metadata"]["units"] = "m";
const DEFAULT_RENDER_MODE: RenderMode = "2d";

const ALLOWED_DOOR_SWINGS: DoorSwing[] = ["left", "right", "double", "sliding", "none"];
const ALLOWED_DOOR_TYPES: DoorType[] = ["single", "double", "sliding", "pocket", "entry"];
const ALLOWED_WINDOW_TYPES: WindowType[] = ["fixed", "casement", "sliding", "picture", "awning"];
const ALLOWED_LINE_STYLES: LineStyle[] = ["solid", "dashed", "dotted"];
const ALLOWED_MATERIAL_CATEGORIES: MaterialCategory[] = ["wall", "floor", "roof", "counter", "fixture", "generic"];
const ALLOWED_ANNOTATION_KINDS: AnnotationKind[] = [
  "label",
  "dimension",
  "materialTag",
  "elevationMarker",
  "sectionMarker",
  "note",
];
const ALLOWED_FIXTURE_KINDS: FixtureKind[] = [
  "sink",
  "toilet",
  "bathtub",
  "shower",
  "stove",
  "refrigerator",
  "island",
  "cabinet",
  "washer",
  "dryer",
  "stairs",
  "column",
  "closet",
  "bed",
  "sofa",
  "table",
  "vanity",
  "dishwasher",
  "generic",
];

const asRecord = (value: unknown): Record<string, unknown> => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }
  return value as Record<string, unknown>;
};

const asMetadataRecord = (value: unknown): Record<string, string | number | boolean | null> | undefined => {
  const source = asRecord(value);
  const entries = Object.entries(source).filter((entry) => {
    const candidate = entry[1];
    return (
      typeof candidate === "string" ||
      typeof candidate === "number" ||
      typeof candidate === "boolean" ||
      candidate === null
    );
  });

  if (entries.length === 0) {
    return undefined;
  }

  return Object.fromEntries(entries) as Record<string, string | number | boolean | null>;
};

const asString = (value: unknown, fallback = ""): string => {
  return typeof value === "string" ? value : fallback;
};

const asNumber = (value: unknown, fallback = 0): number => {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
};

const pickEnum = <T extends string>(value: unknown, allowed: T[], fallback: T): T => {
  return typeof value === "string" && (allowed as string[]).includes(value) ? (value as T) : fallback;
};

const normalizePoint = (value: unknown): Point2D => {
  const source = asRecord(value);
  return {
    x: asNumber(source.x, 0),
    y: asNumber(source.y, 0),
  };
};

const normalizeMetadata = (value: unknown): BlueprintSchema["metadata"] => {
  const source = asRecord(value);
  return {
    title: asString(source.title, "Generated Blueprint"),
    description: asString(source.description, "Blueprint generated by AI assistant."),
    style: asString(source.style) || undefined,
    units: pickEnum(source.units, ["m", "ft"], DEFAULT_UNITS),
    lotWidth: typeof source.lotWidth === "number" ? source.lotWidth : undefined,
    lotDepth: typeof source.lotDepth === "number" ? source.lotDepth : undefined,
  };
};

const normalizeWall = (value: unknown, index: number): Wall => {
  const source = asRecord(value);
  const type = source.type === "interior" ? "interior" : "exterior";

  return {
    id: asString(source.id, "wall_" + index),
    start: normalizePoint(source.start),
    end: normalizePoint(source.end),
    thickness: Math.max(0.05, asNumber(source.thickness, type === "exterior" ? 0.2 : 0.15)),
    type,
    materialId: asString(source.materialId) || undefined,
  };
};

const projectPointToWall = (wall: Wall, offset: number): Point2D => {
  const dx = wall.end.x - wall.start.x;
  const dy = wall.end.y - wall.start.y;
  const length = Math.sqrt(dx * dx + dy * dy);
  if (length <= 0.0001) {
    return { x: wall.start.x, y: wall.start.y };
  }

  const clampedOffset = Math.max(0, Math.min(offset, length));
  const t = clampedOffset / length;
  return {
    x: wall.start.x + dx * t,
    y: wall.start.y + dy * t,
  };
};

const normalizeDoor = (value: unknown, index: number, wallMap: Map<string, Wall>): Door => {
  const source = asRecord(value);
  const wallId = asString(source.wallId) || undefined;
  const width = Math.max(0.5, asNumber(source.width, 0.9));
  const offset = asNumber(source.offset, 0);
  const fallbackFromWall = wallId && wallMap.has(wallId) ? projectPointToWall(wallMap.get(wallId) as Wall, offset) : null;

  return {
    id: asString(source.id, "door_" + index),
    wallId,
    x: asNumber(source.x, fallbackFromWall?.x ?? 0),
    y: asNumber(source.y, fallbackFromWall?.y ?? 0),
    width,
    swing: pickEnum(source.swing, ALLOWED_DOOR_SWINGS, "left"),
    rotation: asNumber(source.rotation, 0),
    type: pickEnum(source.type, ALLOWED_DOOR_TYPES, "single"),
    materialId: asString(source.materialId) || undefined,
    metadata: asMetadataRecord(source.metadata),
    offset: typeof source.offset === "number" ? source.offset : undefined,
    height: typeof source.height === "number" ? source.height : undefined,
  };
};

const normalizeWindow = (value: unknown, index: number, wallMap: Map<string, Wall>): Window => {
  const source = asRecord(value);
  const wallId = asString(source.wallId) || undefined;
  const width = Math.max(0.4, asNumber(source.width, 1));
  const height = Math.max(0.4, asNumber(source.height, 1.2));
  const offset = asNumber(source.offset, 0);
  const fallbackFromWall = wallId && wallMap.has(wallId) ? projectPointToWall(wallMap.get(wallId) as Wall, offset) : null;

  return {
    id: asString(source.id, "window_" + index),
    wallId,
    x: asNumber(source.x, fallbackFromWall?.x ?? 0),
    y: asNumber(source.y, fallbackFromWall?.y ?? 0),
    width,
    height,
    rotation: asNumber(source.rotation, 0),
    type: pickEnum(source.type, ALLOWED_WINDOW_TYPES, "fixed"),
    materialId: asString(source.materialId) || undefined,
    metadata: asMetadataRecord(source.metadata),
    offset: typeof source.offset === "number" ? source.offset : undefined,
    sillHeight: typeof source.sillHeight === "number" ? source.sillHeight : undefined,
  };
};

const normalizeRoom = (value: unknown, index: number): Room => {
  const source = asRecord(value);
  const polygon = Array.isArray(source.polygon) ? source.polygon.map(normalizePoint) : [];
  const safePolygon = polygon.length >= 3 ? polygon : [{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 3 }, { x: 0, y: 3 }];

  return {
    id: asString(source.id, "room_" + index),
    name: asString(source.name, "Room " + (index + 1)),
    label: asString(source.label) || undefined,
    polygon: safePolygon,
    areaSqM: typeof source.areaSqM === "number" ? source.areaSqM : undefined,
    floorMaterial: asString(source.floorMaterial) || undefined,
  };
};

const normalizeFixture = (value: unknown, index: number): Fixture => {
  const source = asRecord(value);
  return {
    id: asString(source.id, "fixture_" + index),
    kind: pickEnum(source.kind, ALLOWED_FIXTURE_KINDS, "generic"),
    x: asNumber(source.x, 0),
    y: asNumber(source.y, 0),
    width: Math.max(0.2, asNumber(source.width, 0.9)),
    height: Math.max(0.2, asNumber(source.height, 0.9)),
    rotation: asNumber(source.rotation, 0),
    roomId: asString(source.roomId) || undefined,
    symbol: asString(source.symbol) || undefined,
    materialId: asString(source.materialId) || undefined,
    metadata: asMetadataRecord(source.metadata),
  };
};

const normalizeAnnotation = (value: unknown, index: number): Annotation => {
  const source = asRecord(value);
  return {
    id: asString(source.id, "annotation_" + index),
    kind: pickEnum(source.kind, ALLOWED_ANNOTATION_KINDS, "note"),
    x: asNumber(source.x, 0),
    y: asNumber(source.y, 0),
    text: asString(source.text, ""),
    targetId: asString(source.targetId) || undefined,
    rotation: typeof source.rotation === "number" ? source.rotation : undefined,
  };
};

const normalizeMaterial = (value: unknown, index: number): MaterialDefinition => {
  const source = asRecord(value);
  return {
    id: asString(source.id, "material_" + index),
    name: asString(source.name, "Material " + (index + 1)),
    category: pickEnum(source.category, ALLOWED_MATERIAL_CATEGORIES, "generic"),
    hatchPattern: asString(source.hatchPattern, "solid"),
    lineStyle: pickEnum(source.lineStyle, ALLOWED_LINE_STYLES, "solid"),
    label: asString(source.label, asString(source.name, "Material " + (index + 1))),
    colorHint: asString(source.colorHint) || undefined,
  };
};

const normalizeRoofZone = (value: unknown, index: number): RoofZone => {
  const source = asRecord(value);
  const polygon = Array.isArray(source.polygon) ? source.polygon.map(normalizePoint) : [];

  return {
    id: asString(source.id, "roof_zone_" + index),
    level: typeof source.level === "number" ? source.level : undefined,
    polygon,
    materialId: asString(source.materialId) || undefined,
    label: asString(source.label) || undefined,
  };
};

const normalizeLegendItem = (value: unknown, index: number): LegendItem => {
  const source = asRecord(value);
  const category = source.category === "material" ? "material" : "symbol";

  return {
    id: asString(source.id, "legend_item_" + index),
    category,
    key: asString(source.key, "item_" + index),
    label: asString(source.label, "Legend Item " + (index + 1)),
    sample: asString(source.sample) || undefined,
  };
};

const normalizeLegend = (value: unknown): LegendDefinition => {
  const source = asRecord(value);
  return {
    title: asString(source.title) || undefined,
    items: Array.isArray(source.items) ? source.items.map(normalizeLegendItem) : [],
  };
};

const normalizeFloor = (value: unknown, index: number): FloorPlan => {
  const source = asRecord(value);
  const walls = Array.isArray(source.walls) ? source.walls.map(normalizeWall) : [];
  const wallMap = new Map(walls.map((wall) => [wall.id, wall]));

  return {
    id: asString(source.id, "floor_" + index),
    level: Math.max(0, Math.round(asNumber(source.level, index))),
    name: asString(source.name, index === 0 ? "Ground Floor" : "Floor " + index),
    ceilingHeight: Math.max(2.2, asNumber(source.ceilingHeight, 2.8)),
    rooms: Array.isArray(source.rooms) ? source.rooms.map(normalizeRoom) : [],
    walls,
    doors: Array.isArray(source.doors) ? source.doors.map((door, doorIndex) => normalizeDoor(door, doorIndex, wallMap)) : [],
    windows: Array.isArray(source.windows)
      ? source.windows.map((windowValue, windowIndex) => normalizeWindow(windowValue, windowIndex, wallMap))
      : [],
    fixtures: Array.isArray(source.fixtures) ? source.fixtures.map(normalizeFixture) : [],
    annotations: Array.isArray(source.annotations) ? source.annotations.map(normalizeAnnotation) : [],
  };
};

export const createDefaultBlueprint = (): BlueprintSchema => {
  const floor: FloorPlan = {
    id: "floor_0",
    level: 0,
    name: "Ground Floor",
    ceilingHeight: 2.8,
    rooms: [
      {
        id: "room_0",
        name: "Room 1",
        polygon: [
          { x: 0, y: 0 },
          { x: 6, y: 0 },
          { x: 6, y: 4 },
          { x: 0, y: 4 },
        ],
      },
    ],
    walls: [
      { id: "wall_0", start: { x: 0, y: 0 }, end: { x: 6, y: 0 }, thickness: 0.2, type: "exterior" },
      { id: "wall_1", start: { x: 6, y: 0 }, end: { x: 6, y: 4 }, thickness: 0.2, type: "exterior" },
      { id: "wall_2", start: { x: 6, y: 4 }, end: { x: 0, y: 4 }, thickness: 0.2, type: "exterior" },
      { id: "wall_3", start: { x: 0, y: 4 }, end: { x: 0, y: 0 }, thickness: 0.2, type: "exterior" },
    ],
    doors: [],
    windows: [],
    fixtures: [],
    annotations: [],
  };

  return {
    metadata: {
      title: "Generated Blueprint",
      description: "Blueprint generated by AI assistant.",
      units: DEFAULT_UNITS,
    },
    floors: [floor],
    materials: [],
    annotations: [],
    roofZones: [],
    legends: [],
    roofHints: {
      type: "gable",
      pitch: "6:12",
    },
    materialHints: {
      wall: "generic_wall",
      roof: "generic_roof",
      floor: "generic_floor",
    },
  };
};

export const normalizeBlueprint = (value: unknown): BlueprintSchema => {
  const source = asRecord(value);
  const floors = Array.isArray(source.floors) ? source.floors.map(normalizeFloor) : [];

  const normalized: BlueprintSchema = {
    metadata: normalizeMetadata(source.metadata),
    floors: floors.length > 0 ? floors : createDefaultBlueprint().floors,
    materials: Array.isArray(source.materials) ? source.materials.map(normalizeMaterial) : [],
    annotations: Array.isArray(source.annotations) ? source.annotations.map(normalizeAnnotation) : [],
    roofZones: Array.isArray(source.roofZones) ? source.roofZones.map(normalizeRoofZone) : [],
    legends: Array.isArray(source.legends) ? source.legends.map((legendValue) => normalizeLegend(legendValue)) : [],
    roofHints: {
      type: asString(asRecord(source.roofHints).type) || undefined,
      pitch: asString(asRecord(source.roofHints).pitch) || undefined,
    },
    materialHints: {
      wall: asString(asRecord(source.materialHints).wall) || undefined,
      roof: asString(asRecord(source.materialHints).roof) || undefined,
      floor: asString(asRecord(source.materialHints).floor) || undefined,
    },
  };

  normalized.floors = normalized.floors.map((floor, floorIndex) => ({
    ...floor,
    fixtures: floor.fixtures ?? [],
    annotations: floor.annotations ?? [],
    rooms: floor.rooms.length > 0 ? floor.rooms : createDefaultBlueprint().floors[0].rooms,
    walls: floor.walls.length > 0 ? floor.walls : createDefaultBlueprint().floors[0].walls,
    id: floor.id || "floor_" + floorIndex,
  }));

  return normalized;
};

export const normalizeProjectBlueprintValue = (value: unknown): BlueprintSchema | null => {
  if (value === null || value === undefined) {
    return null;
  }
  return normalizeBlueprint(value);
};

export const ensureLegendDefinitions = (blueprint: BlueprintSchema): BlueprintSchema => {
  const legends = blueprint.legends ?? [];
  if (legends.length > 0) {
    return blueprint;
  }

  const materialLegend: LegendDefinition = {
    title: "Materials",
    items: (blueprint.materials ?? []).map((material, index) => ({
      id: "legend_material_" + index,
      category: "material",
      key: material.id,
      label: material.label,
      sample: material.hatchPattern,
    })),
  };

  return {
    ...blueprint,
    legends: [materialLegend],
  };
};

export const PROJECT_RENDER_MODE_DEFAULT = DEFAULT_RENDER_MODE;
export const PROJECT_BLUEPRINT_UNITS_DEFAULT = DEFAULT_UNITS;
